language: node_js
node_js:
  - '14.6.0'
addons:
  chrome: stable
  sonarcloud:
    organization: "alu0100824810" # the key of the org you chose at step #3
    token:
      secure: $SONAR # encrypted value of your token
branches:
  only:
  - develop
  - /^release-[0-999].[0-999]$/
  - master
script:
  - ng test
  - sonar-scanner
#  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=alu0100824810 -Dsonar.login=$SONAR