language: node_js
node_js:
  - "12"

addons:
   sonarcloud:
    organization: "alu0100824810"
    token:
      secure: $SONAR
branches:
  only:
  - develop
  - /^release-[0-999].[0-999]$/
  - master
script:
  - npm run test && sonar-scanner
